import type fr from './fr'

type Strings = typeof fr

const en: Strings = {
  PropertyPaneDescription: 'Directory Settings',
  ViewGroupName: 'Display',
  DefaultViewLabel: 'Default view',
  ViewTrombinoscope: 'Card View',
  ViewList: 'List View',
  SortOrderLabel: 'Sort users',
  SortLastNameAsc: 'Alphabetical Last Name',
  SortLastNameDesc: 'Reverse Last Name',
  SortFirstNameAsc: 'Alphabetical First Name',
  SortFirstNameDesc: 'Reverse First Name',
  SortRandom: 'Random',
  FilterGroupName: 'Filters',
  NoFilter: 'No filter configured',
  FilterLabel: 'Filter',
  FilterFieldLabel: 'Field',
  FilterTextFieldLabel: 'Label',
  AddFilter: 'Add filter',
  RemoveFilter: 'Remove',
  FieldPhoto: 'Photo',
  FieldName: 'Last Name',
  FieldFirstName: 'First Name',
  FieldEmail: 'Email',
  FieldPhone: 'Phone',
  FieldJobTitle: 'Job Title',
  FieldDepartment: 'Department',
  FieldOfficeLocation: 'Office Location',
  FieldManager: 'Manager',
  FieldOutlook: 'Outlook',
  FieldTeams: 'Teams',
  CustomFieldsCardGroup: 'Card View',
  CustomFieldsListGroup: 'List View',
  CustomFieldsModalGroup: 'Modal',
  CustomFieldsEntraID: 'Entra ID Fields',
  CustomFieldDropdown: 'Entra ID Field',
  CustomFieldLabelInput: 'Custom label (optional)',
  AddCustomField: 'Add Entra ID field',
  RemoveCustomField: 'Remove this field',
  SelectPlaceholder: 'Select...',
  CustomFieldsPrefix: '— Entra ID Fields',
  SearchPlaceholder: 'Search a collaborator...',
  ResultCount: '{0} result(s)',
  LoadMore: 'Load more',
  ViewProfile: 'View profile',
  ClickForDetails: 'Click for details',
  HeaderCollaborator: 'Collaborator',
  HeaderJobTitle: 'Job Title',
  HeaderEmail: 'Email',
  HeaderPhone: 'Phone',
  HeaderDepartment: 'Department',
  HeaderLocation: 'Location',
  HeaderManager: 'Manager',
  SendEmail: 'Send email',
  ContactViaTeams: 'Contact via Teams',
  LabelDepartment: 'Department',
  LabelLocation: 'Location',
  LabelManager: 'Manager',
  CloseModal: 'Close',
  ErrorLoading: 'Unable to load directory data. Please try again.',
  ErrorBoundaryMessage: 'An unexpected error occurred. Please try again.',
  Retry: 'Retry',
  NoResults: 'No collaborators found',
  EmptyStateHint: 'Try modifying your search criteria or filters.',
  LoadingText: 'Loading...',
  ResultsLabel: 'Results:',
  CollaboratorSingular: 'collaborator',
  CollaboratorPlural: 'collaborators',
  ExportCsv: 'Export to CSV',
  ClearSearch: 'Clear search',
  FilterSearch: 'Search…',
  PropertyPaneHeader: 'Settings',
  FilterLabelInput: 'Display label',
  None: 'None',
  RemoveFilterLabel: 'Remove this filter',
  // EntraID field labels
  EntraField_aboutMe: 'About me',
  EntraField_birthday: 'Birthday',
  EntraField_interests: 'Interests',
  EntraField_pastProjects: 'Past projects',
  EntraField_responsibilities: 'Responsibilities',
  EntraField_schools: 'Schools',
  EntraField_skills: 'Skills',
  EntraField_streetAddress: 'Street address',
  EntraField_city: 'City',
  EntraField_state: 'State / Region',
  EntraField_postalCode: 'Postal code',
  EntraField_country: 'Country',
  EntraField_businessPhones: 'Business phone',
  EntraField_faxNumber: 'Fax',
  EntraField_otherMails: 'Other emails',
  EntraField_imAddresses: 'IM addresses',
  EntraField_mySite: 'Personal site',
  EntraField_companyName: 'Company',
  EntraField_employeeId: 'Employee ID',
  EntraField_employeeType: 'Employee type',
  EntraField_employeeHireDate: 'Hire date (MS)',
  EntraField_hireDate: 'Hire date (SP)',
  EntraField_employeeLeaveDateTime: 'Leave date',
  EntraField_division: 'Division',
  EntraField_costCenter: 'Cost center',
  EntraField_preferredLanguage: 'Language',
  EntraField_usageLocation: 'Usage location',
  EntraField_createdDateTime: 'Created date',
  EntraField_ageGroup: 'Age group',
  EntraField_consentProvidedForMinor: 'Minor consent',
  EntraField_legalAgeGroupClassification: 'Legal age classification',
  EntraField_externalUserState: 'External user state',
  EntraField_mailNickname: 'Mail alias',
  EntraField_lastPasswordChangeDateTime: 'Last password change',
  EntraField_onPremisesDistinguishedName: 'DN On-Prem',
  EntraField_onPremisesDomainName: 'On-Prem domain',
  EntraField_onPremisesSamAccountName: 'SAM account',
  EntraField_onPremisesUserPrincipalName: 'On-Prem UPN',
  EntraField_extensionAttribute1: 'Extension Attribute 1',
  EntraField_extensionAttribute2: 'Extension Attribute 2',
  EntraField_extensionAttribute3: 'Extension Attribute 3',
  EntraField_extensionAttribute4: 'Extension Attribute 4',
  EntraField_extensionAttribute5: 'Extension Attribute 5',
  EntraField_extensionAttribute6: 'Extension Attribute 6',
  EntraField_extensionAttribute7: 'Extension Attribute 7',
  EntraField_extensionAttribute8: 'Extension Attribute 8',
  EntraField_extensionAttribute9: 'Extension Attribute 9',
  EntraField_extensionAttribute10: 'Extension Attribute 10',
  EntraField_extensionAttribute11: 'Extension Attribute 11',
  EntraField_extensionAttribute12: 'Extension Attribute 12',
  EntraField_extensionAttribute13: 'Extension Attribute 13',
  EntraField_extensionAttribute14: 'Extension Attribute 14',
  EntraField_extensionAttribute15: 'Extension Attribute 15',
  // Property pane tabs
  TabCard: 'Trombinoscope',
  TabList: 'List',
  TabModal: 'Modal',
  ViewTabLabel: 'View to configure',
  // DnD field selector
  DnD_AvailableFields: 'Available fields',
  DnD_DisplayOrder: 'Display order',
  DnD_DragHint: 'Drag and drop to reorder',
  DnD_StandardGroup: 'Standard',
  DnD_ExtAttrGroup: 'Extension attributes',
  DnD_AddExtAttr: 'Add an attribute…',
  DnD_AddField: 'Add',
  DnD_RemoveField: 'Remove',
  DnD_Group_Profile: 'Profile',
  DnD_Group_Contact: 'Contact',
  DnD_Group_Company: 'Company',
  DnD_Group_Region: 'Language & Region',
  DnD_Group_OnPrem: 'On-premises',
  DnD_Group_Other: 'Other',
  DnD_NoSelection: 'No fields selected.',
  Lang_fr: 'French label',
  Lang_en: 'English label',
  DirectoryRegionLabel: 'SharePoint Directory',
}

export default en
