const fr = {
  PropertyPaneDescription: "Configuration de l'annuaire",
  ViewGroupName: 'Affichage',
  DefaultViewLabel: 'Vue par défaut',
  ViewTrombinoscope: 'Vue Trombinoscope',
  ViewList: 'Vue Liste',
  SortOrderLabel: 'Tri des utilisateurs',
  SortLastNameAsc: 'Alphabétique Nom',
  SortLastNameDesc: 'Anti-alphabétique Nom',
  SortFirstNameAsc: 'Alphabétique Prénom',
  SortFirstNameDesc: 'Anti-alphabétique Prénom',
  SortRandom: 'Aléatoire',
  FilterGroupName: 'Filtres',
  NoFilter: 'Aucun filtre configuré',
  FilterLabel: 'Filtre',
  FilterFieldLabel: 'Champ',
  FilterTextFieldLabel: 'Libellé',
  AddFilter: 'Ajouter un filtre',
  RemoveFilter: 'Supprimer',
  FieldPhoto: 'Photo',
  FieldName: 'Nom',
  FieldFirstName: 'Prénom',
  FieldEmail: 'E-mail',
  FieldPhone: 'Téléphone',
  FieldJobTitle: 'Poste',
  FieldDepartment: 'Département',
  FieldOfficeLocation: 'Localisation',
  FieldManager: 'Manager',
  FieldOutlook: 'Outlook',
  FieldTeams: 'Teams',
  CustomFieldsCardGroup: 'Vue Trombinoscope',
  CustomFieldsListGroup: 'Vue Liste',
  CustomFieldsModalGroup: 'Vue Modale',
  CustomFieldsEntraID: 'Champs EntraID',
  CustomFieldDropdown: 'Champ EntraID',
  CustomFieldLabelInput: 'Libellé personnalisé (optionnel)',
  CustomFieldLabelFr: 'Libellé (FR)',
  CustomFieldLabelEn: 'Libellé (EN)',
  AddCustomField: 'Ajouter un champ EntraID',
  RemoveCustomField: 'Supprimer ce champ',
  SelectPlaceholder: 'Sélectionner...',
  CustomFieldsPrefix: '— Champs EntraID',
  SearchPlaceholder: 'Rechercher un collaborateur...',
  ResultCount: '{0} résultat(s)',
  LoadMore: 'Voir plus de collaborateurs',
  ViewProfile: 'Voir la fiche',
  ClickForDetails: 'Cliquez pour les détails',
  HeaderCollaborator: 'Collaborateur',
  HeaderJobTitle: 'Poste',
  HeaderEmail: 'E-mail',
  HeaderPhone: 'Téléphone',
  HeaderDepartment: 'Département',
  HeaderLocation: 'Localisation',
  HeaderManager: 'Manager',
  SendEmail: 'Envoyer un email',
  ContactViaTeams: 'Contacter via Teams',
  LabelDepartment: 'Département',
  LabelLocation: 'Localisation',
  LabelManager: 'Manager',
  CloseModal: 'Fermer',
  ErrorLoading:
    "Impossible de charger les données de l'annuaire. Veuillez réessayer.",
  ErrorBoundaryMessage:
    "Une erreur inattendue s'est produite. Veuillez réessayer.",
  Retry: 'Réessayer',
  NoResults: 'Aucun collaborateur trouvé',
  EmptyStateHint: 'Essayez de modifier vos critères de recherche ou vos filtres.',
  AccessDeniedMessage: "Vous n'avez pas les droits nécessaires pour accéder à cet annuaire.",
  LoadingText: 'Chargement...',
  ResultsLabel: 'Résultats :',
  CollaboratorSingular: 'collaborateur',
  CollaboratorPlural: 'collaborateurs',
  ExportCsv: 'Exporter en CSV',
  ClearSearch: 'Effacer la recherche',
  PropertyPaneHeader: 'Paramètres',
  FilterLabelInput: 'Libellé affiché',
  None: 'Aucun',
  RemoveFilterLabel: 'Supprimer ce filtre',
  // EntraID field labels
  EntraField_aboutMe: 'À propos',
  EntraField_birthday: 'Date de naissance',
  EntraField_interests: "Centres d'intérêt",
  EntraField_pastProjects: 'Projets passés',
  EntraField_responsibilities: 'Responsabilités',
  EntraField_schools: 'Écoles',
  EntraField_skills: 'Compétences',
  EntraField_streetAddress: 'Adresse',
  EntraField_city: 'Ville',
  EntraField_state: 'Région',
  EntraField_postalCode: 'Code postal',
  EntraField_country: 'Pays',
  EntraField_businessPhones: 'Téléphone pro',
  EntraField_faxNumber: 'Fax',
  EntraField_otherMails: 'Autres emails',
  EntraField_imAddresses: 'Adresses IM',
  EntraField_mySite: 'Site personnel',
  EntraField_companyName: 'Société',
  EntraField_employeeId: 'ID Employé',
  EntraField_employeeType: "Type d'employé",
  EntraField_employeeHireDate: "Date d'embauche (MS)",
  EntraField_hireDate: "Date d'embauche (SP)",
  EntraField_employeeLeaveDateTime: 'Date de départ',
  EntraField_division: 'Division',
  EntraField_costCenter: 'Centre de coût',
  EntraField_preferredLanguage: 'Langue',
  EntraField_usageLocation: "Localisation d'usage",
  EntraField_createdDateTime: 'Date de création',
  EntraField_ageGroup: "Groupe d'âge",
  EntraField_consentProvidedForMinor: 'Consentement mineur',
  EntraField_legalAgeGroupClassification: 'Classification âge légal',
  EntraField_externalUserState: 'État utilisateur externe',
  EntraField_mailNickname: 'Alias mail',
  EntraField_lastPasswordChangeDateTime: 'Dernier changement MDP',
  EntraField_onPremisesDistinguishedName: 'DN On-Prem',
  EntraField_onPremisesDomainName: 'Domaine On-Prem',
  EntraField_onPremisesSamAccountName: 'SAM Account',
  EntraField_onPremisesUserPrincipalName: 'UPN On-Prem',
  EntraField_extensionAttribute1: 'Extension Attribute 1',
  EntraField_extensionAttribute2: 'Extension Attribute 2',
  EntraField_extensionAttribute3: 'Extension Attribute 3',
  EntraField_extensionAttribute4: 'Extension Attribute 4',
  EntraField_extensionAttribute5: 'Extension Attribute 5',
  EntraField_extensionAttribute6: 'Extension Attribute 6',
  EntraField_extensionAttribute7: 'Extension Attribute 7',
  EntraField_extensionAttribute8: 'Extension Attribute 8',
  EntraField_extensionAttribute9: 'Extension Attribute 9',
  EntraField_extensionAttribute10: 'Extension Attribute 10',
  EntraField_extensionAttribute11: 'Extension Attribute 11',
  EntraField_extensionAttribute12: 'Extension Attribute 12',
  EntraField_extensionAttribute13: 'Extension Attribute 13',
  EntraField_extensionAttribute14: 'Extension Attribute 14',
  EntraField_extensionAttribute15: 'Extension Attribute 15',
  // Property pane tabs
  TabCard: 'Trombinoscope',
  TabList: 'Liste',
  TabModal: 'Modale',
  ViewTabLabel: 'Vue à configurer',
  // DnD field selector
  DnD_AvailableFields: 'Champs disponibles',
  DnD_DisplayOrder: "Ordre d'affichage",
  DnD_DragHint: 'Glisser-déposer pour réordonner',
  DnD_StandardGroup: 'Standards',
  DnD_ExtAttrGroup: "Attributs d'extension",
  DnD_AddExtAttr: 'Ajouter un attribut…',
  DnD_AddField: 'Ajouter',
  DnD_RemoveField: 'Retirer',
  DnD_LabelFr: 'Libellé FR',
  DnD_LabelEn: 'Libellé EN',
  DnD_Group_Profile: 'Profil',
  DnD_Group_Contact: 'Coordonnées',
  DnD_Group_Company: 'Entreprise',
  DnD_Group_Region: 'Langue & Région',
  DnD_Group_OnPrem: 'On-premises',
  DnD_Group_Other: 'Divers',
  DnD_NoSelection: 'Aucun champ sélectionné.',
  DirectoryRegionLabel: 'Annuaire SharePoint',
}

const en: typeof fr = {
  PropertyPaneDescription: 'Directory Settings',
  ViewGroupName: 'Display',
  DefaultViewLabel: 'Default view',
  ViewTrombinoscope: 'Card View',
  ViewList: 'List View',
  SortOrderLabel: 'Sort users',
  SortLastNameAsc: 'Alphabetical Last Name',
  SortLastNameDesc: 'Reverse Last Name',
  SortFirstNameAsc: 'Alphabetical First Name',
  SortFirstNameDesc: 'Reverse First Name',
  SortRandom: 'Random',
  FilterGroupName: 'Filters',
  NoFilter: 'No filter configured',
  FilterLabel: 'Filter',
  FilterFieldLabel: 'Field',
  FilterTextFieldLabel: 'Label',
  AddFilter: 'Add filter',
  RemoveFilter: 'Remove',
  FieldPhoto: 'Photo',
  FieldName: 'Last Name',
  FieldFirstName: 'First Name',
  FieldEmail: 'Email',
  FieldPhone: 'Phone',
  FieldJobTitle: 'Job Title',
  FieldDepartment: 'Department',
  FieldOfficeLocation: 'Office Location',
  FieldManager: 'Manager',
  FieldOutlook: 'Outlook',
  FieldTeams: 'Teams',
  CustomFieldsCardGroup: 'Card View',
  CustomFieldsListGroup: 'List View',
  CustomFieldsModalGroup: 'Modal',
  CustomFieldsEntraID: 'Entra ID Fields',
  CustomFieldDropdown: 'Entra ID Field',
  CustomFieldLabelInput: 'Custom label (optional)',
  CustomFieldLabelFr: 'Label (FR)',
  CustomFieldLabelEn: 'Label (EN)',
  AddCustomField: 'Add Entra ID field',
  RemoveCustomField: 'Remove this field',
  SelectPlaceholder: 'Select...',
  CustomFieldsPrefix: '— Entra ID Fields',
  SearchPlaceholder: 'Search a collaborator...',
  ResultCount: '{0} result(s)',
  LoadMore: 'Load more',
  ViewProfile: 'View profile',
  ClickForDetails: 'Click for details',
  HeaderCollaborator: 'Collaborator',
  HeaderJobTitle: 'Job Title',
  HeaderEmail: 'Email',
  HeaderPhone: 'Phone',
  HeaderDepartment: 'Department',
  HeaderLocation: 'Location',
  HeaderManager: 'Manager',
  SendEmail: 'Send email',
  ContactViaTeams: 'Contact via Teams',
  LabelDepartment: 'Department',
  LabelLocation: 'Location',
  LabelManager: 'Manager',
  CloseModal: 'Close',
  ErrorLoading: 'Unable to load directory data. Please try again.',
  ErrorBoundaryMessage: 'An unexpected error occurred. Please try again.',
  Retry: 'Retry',
  NoResults: 'No collaborators found',
  EmptyStateHint: 'Try modifying your search criteria or filters.',
  AccessDeniedMessage: 'You do not have the necessary permissions to access this directory.',
  LoadingText: 'Loading...',
  ResultsLabel: 'Results:',
  CollaboratorSingular: 'collaborator',
  CollaboratorPlural: 'collaborators',
  ExportCsv: 'Export to CSV',
  ClearSearch: 'Clear search',
  PropertyPaneHeader: 'Settings',
  FilterLabelInput: 'Display label',
  None: 'None',
  RemoveFilterLabel: 'Remove this filter',
  // EntraID field labels
  EntraField_aboutMe: 'About me',
  EntraField_birthday: 'Birthday',
  EntraField_interests: 'Interests',
  EntraField_pastProjects: 'Past projects',
  EntraField_responsibilities: 'Responsibilities',
  EntraField_schools: 'Schools',
  EntraField_skills: 'Skills',
  EntraField_streetAddress: 'Street address',
  EntraField_city: 'City',
  EntraField_state: 'State / Region',
  EntraField_postalCode: 'Postal code',
  EntraField_country: 'Country',
  EntraField_businessPhones: 'Business phone',
  EntraField_faxNumber: 'Fax',
  EntraField_otherMails: 'Other emails',
  EntraField_imAddresses: 'IM addresses',
  EntraField_mySite: 'Personal site',
  EntraField_companyName: 'Company',
  EntraField_employeeId: 'Employee ID',
  EntraField_employeeType: 'Employee type',
  EntraField_employeeHireDate: 'Hire date (MS)',
  EntraField_hireDate: 'Hire date (SP)',
  EntraField_employeeLeaveDateTime: 'Leave date',
  EntraField_division: 'Division',
  EntraField_costCenter: 'Cost center',
  EntraField_preferredLanguage: 'Language',
  EntraField_usageLocation: 'Usage location',
  EntraField_createdDateTime: 'Created date',
  EntraField_ageGroup: 'Age group',
  EntraField_consentProvidedForMinor: 'Minor consent',
  EntraField_legalAgeGroupClassification: 'Legal age classification',
  EntraField_externalUserState: 'External user state',
  EntraField_mailNickname: 'Mail alias',
  EntraField_lastPasswordChangeDateTime: 'Last password change',
  EntraField_onPremisesDistinguishedName: 'DN On-Prem',
  EntraField_onPremisesDomainName: 'On-Prem domain',
  EntraField_onPremisesSamAccountName: 'SAM account',
  EntraField_onPremisesUserPrincipalName: 'On-Prem UPN',
  EntraField_extensionAttribute1: 'Extension Attribute 1',
  EntraField_extensionAttribute2: 'Extension Attribute 2',
  EntraField_extensionAttribute3: 'Extension Attribute 3',
  EntraField_extensionAttribute4: 'Extension Attribute 4',
  EntraField_extensionAttribute5: 'Extension Attribute 5',
  EntraField_extensionAttribute6: 'Extension Attribute 6',
  EntraField_extensionAttribute7: 'Extension Attribute 7',
  EntraField_extensionAttribute8: 'Extension Attribute 8',
  EntraField_extensionAttribute9: 'Extension Attribute 9',
  EntraField_extensionAttribute10: 'Extension Attribute 10',
  EntraField_extensionAttribute11: 'Extension Attribute 11',
  EntraField_extensionAttribute12: 'Extension Attribute 12',
  EntraField_extensionAttribute13: 'Extension Attribute 13',
  EntraField_extensionAttribute14: 'Extension Attribute 14',
  EntraField_extensionAttribute15: 'Extension Attribute 15',
  // Property pane tabs
  TabCard: 'Trombinoscope',
  TabList: 'List',
  TabModal: 'Modal',
  ViewTabLabel: 'View to configure',
  // DnD field selector
  DnD_AvailableFields: 'Available fields',
  DnD_DisplayOrder: 'Display order',
  DnD_DragHint: 'Drag and drop to reorder',
  DnD_StandardGroup: 'Standard',
  DnD_ExtAttrGroup: 'Extension attributes',
  DnD_AddExtAttr: 'Add an attribute…',
  DnD_AddField: 'Add',
  DnD_RemoveField: 'Remove',
  DnD_LabelFr: 'Label FR',
  DnD_LabelEn: 'Label EN',
  DnD_Group_Profile: 'Profile',
  DnD_Group_Contact: 'Contact',
  DnD_Group_Company: 'Company',
  DnD_Group_Region: 'Language & Region',
  DnD_Group_OnPrem: 'On-premises',
  DnD_Group_Other: 'Other',
  DnD_NoSelection: 'No fields selected.',
  DirectoryRegionLabel: 'SharePoint Directory',
}

export type Strings = typeof fr

// ── Locale registry — add new languages here ────────────────────────────────
const locales: Record<string, Strings> = { fr, en }

let current: Strings = fr

export const strings: Strings = new Proxy({} as Strings, {
  get(_target, prop: keyof Strings) {
    return current[prop]
  },
})

/** Call once at startup with the SharePoint currentCultureName (e.g. "fr-fr", "en-us"). */
export function setLanguage(locale: string): void {
  const lang = (locale || '').split('-')[0].toLowerCase()
  current = locales[lang] || en
}
