"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fr = {
    PropertyPaneDescription: "Configuration de l'annuaire",
    ViewGroupName: 'Affichage',
    DefaultViewLabel: 'Vue par défaut',
    ViewTrombinoscope: 'Vue Trombinoscope',
    ViewList: 'Vue Liste',
    SortOrderLabel: 'Tri des utilisateurs',
    SortLastNameAsc: 'Alphabétique Nom',
    SortLastNameDesc: 'Anti-alphabétique Nom',
    SortFirstNameAsc: 'Alphabétique Prénom',
    SortFirstNameDesc: 'Anti-alphabétique Prénom',
    SortRandom: 'Aléatoire',
    FilterGroupName: 'Filtres',
    NoFilter: 'Aucun filtre configuré',
    FilterLabel: 'Filtre',
    FilterFieldLabel: 'Champ',
    FilterTextFieldLabel: 'Libellé',
    AddFilter: 'Ajouter un filtre',
    RemoveFilter: 'Supprimer',
    FieldPhoto: 'Photo',
    FieldName: 'Nom',
    FieldFirstName: 'Prénom',
    FieldEmail: 'E-mail',
    FieldPhone: 'Téléphone',
    FieldJobTitle: 'Poste',
    FieldDepartment: 'Département',
    FieldOfficeLocation: 'Localisation',
    FieldManager: 'Manager',
    FieldOutlook: 'Outlook',
    FieldTeams: 'Teams',
    CustomFieldsCardGroup: 'Vue Trombinoscope',
    CustomFieldsListGroup: 'Vue Liste',
    CustomFieldsModalGroup: 'Vue Modale',
    CustomFieldsEntraID: 'Champs EntraID',
    CustomFieldDropdown: 'Champ EntraID',
    CustomFieldLabelInput: 'Libellé personnalisé (optionnel)',
    AddCustomField: 'Ajouter un champ EntraID',
    RemoveCustomField: 'Supprimer ce champ',
    SelectPlaceholder: 'Sélectionner...',
    CustomFieldsPrefix: '— Champs EntraID',
    SearchPlaceholder: 'Rechercher un collaborateur...',
    ResultCount: '{0} résultat(s)',
    LoadMore: 'Voir plus de collaborateurs',
    ViewProfile: 'Voir la fiche',
    ClickForDetails: 'Cliquez pour les détails',
    HeaderCollaborator: 'Collaborateur',
    HeaderJobTitle: 'Poste',
    HeaderEmail: 'E-mail',
    HeaderPhone: 'Téléphone',
    HeaderDepartment: 'Département',
    HeaderLocation: 'Localisation',
    HeaderManager: 'Manager',
    SendEmail: 'Envoyer un email',
    ContactViaTeams: 'Contacter via Teams',
    LabelDepartment: 'Département',
    LabelLocation: 'Localisation',
    LabelManager: 'Manager',
    CloseModal: 'Fermer',
    ErrorLoading: "Impossible de charger les données de l'annuaire. Veuillez réessayer.",
    ErrorBoundaryMessage: "Une erreur inattendue s'est produite. Veuillez réessayer.",
    Retry: 'Réessayer',
    NoResults: 'Aucun collaborateur trouvé',
    EmptyStateHint: 'Essayez de modifier vos critères de recherche ou vos filtres.',
    AccessDeniedMessage: "Vous n'avez pas les droits nécessaires pour accéder à cet annuaire.",
    LoadingText: 'Chargement...',
    ResultsLabel: 'Résultats :',
    CollaboratorSingular: 'collaborateur',
    CollaboratorPlural: 'collaborateurs',
    ExportCsv: 'Exporter en CSV',
    ClearSearch: 'Effacer la recherche',
    PropertyPaneHeader: 'Paramètres',
    FilterLabelInput: 'Libellé affiché',
    None: 'Aucun',
    RemoveFilterLabel: 'Supprimer ce filtre',
    // EntraID field labels
    EntraField_aboutMe: 'À propos',
    EntraField_birthday: 'Date de naissance',
    EntraField_interests: "Centres d'intérêt",
    EntraField_pastProjects: 'Projets passés',
    EntraField_responsibilities: 'Responsabilités',
    EntraField_schools: 'Écoles',
    EntraField_skills: 'Compétences',
    EntraField_streetAddress: 'Adresse',
    EntraField_city: 'Ville',
    EntraField_state: 'Région',
    EntraField_postalCode: 'Code postal',
    EntraField_country: 'Pays',
    EntraField_businessPhones: 'Téléphone pro',
    EntraField_faxNumber: 'Fax',
    EntraField_otherMails: 'Autres emails',
    EntraField_imAddresses: 'Adresses IM',
    EntraField_mySite: 'Site personnel',
    EntraField_companyName: 'Société',
    EntraField_employeeId: 'ID Employé',
    EntraField_employeeType: "Type d'employé",
    EntraField_employeeHireDate: "Date d'embauche (MS)",
    EntraField_hireDate: "Date d'embauche (SP)",
    EntraField_employeeLeaveDateTime: 'Date de départ',
    EntraField_division: 'Division',
    EntraField_costCenter: 'Centre de coût',
    EntraField_preferredLanguage: 'Langue',
    EntraField_usageLocation: "Localisation d'usage",
    EntraField_createdDateTime: 'Date de création',
    EntraField_ageGroup: "Groupe d'âge",
    EntraField_consentProvidedForMinor: 'Consentement mineur',
    EntraField_legalAgeGroupClassification: 'Classification âge légal',
    EntraField_externalUserState: 'État utilisateur externe',
    EntraField_mailNickname: 'Alias mail',
    EntraField_lastPasswordChangeDateTime: 'Dernier changement MDP',
    EntraField_onPremisesDistinguishedName: 'DN On-Prem',
    EntraField_onPremisesDomainName: 'Domaine On-Prem',
    EntraField_onPremisesSamAccountName: 'SAM Account',
    EntraField_onPremisesUserPrincipalName: 'UPN On-Prem',
    EntraField_extensionAttribute1: 'Extension Attribute 1',
    EntraField_extensionAttribute2: 'Extension Attribute 2',
    EntraField_extensionAttribute3: 'Extension Attribute 3',
    EntraField_extensionAttribute4: 'Extension Attribute 4',
    EntraField_extensionAttribute5: 'Extension Attribute 5',
    EntraField_extensionAttribute6: 'Extension Attribute 6',
    EntraField_extensionAttribute7: 'Extension Attribute 7',
    EntraField_extensionAttribute8: 'Extension Attribute 8',
    EntraField_extensionAttribute9: 'Extension Attribute 9',
    EntraField_extensionAttribute10: 'Extension Attribute 10',
    EntraField_extensionAttribute11: 'Extension Attribute 11',
    EntraField_extensionAttribute12: 'Extension Attribute 12',
    EntraField_extensionAttribute13: 'Extension Attribute 13',
    EntraField_extensionAttribute14: 'Extension Attribute 14',
    EntraField_extensionAttribute15: 'Extension Attribute 15',
    // Property pane tabs
    TabCard: 'Trombinoscope',
    TabList: 'Liste',
    TabModal: 'Modale',
    ViewTabLabel: 'Vue à configurer',
    // DnD field selector
    DnD_AvailableFields: 'Champs disponibles',
    DnD_DisplayOrder: "Ordre d'affichage",
    DnD_DragHint: 'Glisser-déposer pour réordonner',
    DnD_StandardGroup: 'Standards',
    DnD_ExtAttrGroup: "Attributs d'extension",
    DnD_AddExtAttr: 'Ajouter un attribut…',
    DnD_AddField: 'Ajouter',
    DnD_RemoveField: 'Retirer',
    DnD_Group_Profile: 'Profil',
    DnD_Group_Contact: 'Coordonnées',
    DnD_Group_Company: 'Entreprise',
    DnD_Group_Region: 'Langue & Région',
    DnD_Group_OnPrem: 'On-premises',
    DnD_Group_Other: 'Divers',
    DnD_NoSelection: 'Aucun champ sélectionné.',
    Lang_fr: 'Label français',
    Lang_en: 'Label anglais',
    DirectoryRegionLabel: 'Annuaire SharePoint',
};
exports.default = fr;
//# sourceMappingURL=fr.js.map